project:
  type: website

website:
  title: "Louise A. Huuki-Myers"
  site-url: https://lahuuki.github.io/
  description: "Louise's Blog"
  navbar:
    right:
      - text: "About Me"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
      - icon: github
        href: https://github.com/lahuuki/
      - icon: linkedin
        href: https://www.linkedin.com/in/louise-huuki/
      - icon: twitter
        href: https://twitter.com/lahuuki/
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css
    
editor: visual

execute:
  freeze: true



